[[redirects]]
  from = "/"
  to = "/ja/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/ja/:splat"
  status = 301
  force = false

[[headers]]
  for = "/*"
  [headers.values]
    Content-Language = "ja, en, ja-simple"
